---

- name: Download and checkout git OKD version 3.11
  git:
    repo: 'https://github.com/openshift/openshift-ansible'
    dest: /root/openshift-ansible-3.11
    clone: yes
    version: release-3.11
  tags: git_okd


- name: Copy ocp_hosts /etc/ansible
  copy:
    src: ocp_new_3.11
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
  tags: ansible_hosts


